---
title: "ASP_model_simulation"
author: "Cher"
date: "9/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gtools)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(ggpubr)
rm(list = ls())

# read model simulation data
# skip second line (params)
df <- read.csv("./MODEL320200928222753.txt", header = TRUE,  sep = ",")[-1,]

param <- as.character(read.csv("./MODEL220200928222151.txt", header = FALSE,  sep = ",")[2,1])

# data summary
df_summary <- df %>%
  gather(key='P_type', value='prop_DO', DOC:POI) %>%
  mutate(P_type=as.factor(P_type), 
         prop_DO=as.numeric(prop_DO),
         syn_voice = as.factor(ifelse((P_type=="DOC")|(P_type=="DOI"), 
                            "DO", "PO")),
         syn_corr = as.factor(ifelse((P_type=="DOC")|(P_type=="POC"), 
                            "C", "I"))) %>%
  group_by(P_type, syn_voice, syn_corr) %>%
  get_summary_stats(type = 'mean_se')

# change name
#levels(df_summary$P_type) <- c("S1C","S1I","S2C","S2I")
#levels(df_summary$syn_voice) <- c("S1","S2")

model_plot <- df_summary %>%
  ggplot(aes(x=syn_voice, y=mean,  group=syn_corr, fill=syn_corr)) + 
  geom_col(stat="identity", position='dodge2', 
           width = .7, colour="black") + 
  #geom_text(aes(label = round(mean,2)), 
  #          position = position_dodge(0.7),  vjust = 5) +
  geom_errorbar(aes(ymin = mean-se, 
                    ymax = mean+se), 
                width=0.1, 
                position=position_dodge(width=0.7)) +
  #ylim(c(0,1))  + 
  ggtitle('Results of ACT-R Declarative Model', 
          subtitle = param) + 
  labs(x = "Prime Conditions", 
       y='Proportion of DO descriptions') +
  scale_fill_manual(values=c("white", "gray"), labels = c("Correct", "Incorrect"), name = "Syntactic Correctness") +
  theme_gray(base_size = 20)

model_plot
```


```{r}

```